kind = "web"
previewPath = "/"
title = "Smart Portal RT 005 Tegalsari"
version = "1.0.0"
id = "artifacts/smart-portal-rt"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25803

[services.development]
run = "pnpm --filter @workspace/smart-portal-rt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-portal-rt", "run", "build" ]
publicDir = "artifacts/smart-portal-rt/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25803"
BASE_PATH = "/"
